name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  API_ENDPOINT: https://tournoix.ch/api
  APP_URL: https://tournoix.ch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: jetli/trunk-action@v0.4.0
      with:
        version: 'latest'
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: wasm32-unknown-unknown

    - uses: Swatinem/rust-cache@v2
      with:
        save-if: false
        cache-directories: "./backend/.cargo\n ./backend/target\n ./ui/.cargo\n ./ui/target"
        shared-key: "rust_cache"
    
    - name: Build frontend
      run: cd ./ui && mv ./.env.example ./.env && npm i && npx tailwindcss -i ./style.scss -o ./output.scss --minify && trunk build --release
      
    - name: Build backend
      run: cd ./backend && cargo build --release

    - name: Cleanup
      run: rm -rf ./backend/target

    - name: Move frontend files
      run: cp -r ./ui/dist/* ./backend/public/

    - name: Deploy in production
      continue-on-error: true
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          username: ${{ secrets.SFTP_USER }}
          server: ${{ secrets.SFTP_HOST }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          local_path: './backend/*'
          remote_path: '/'
          sftp_only: true
    
