name: Rust

on:
  push:
    branches: [ "tests" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Setup MySQL
      # You may pin to the exact commit or the version.
      # uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
      uses: mirromutth/mysql-action@v1.1
      with:
        # MYSQL_ROOT_PASSWORD - root superuser password
        mysql root password: "Password"# optional, default is 
        # MYSQL_DATABASE - name for the default database that is created
        mysql database: "tournoix_db"
    - name: Run tests
      run: cargo test --verbose
