name: MySQL service
on: push

env:
  DB_DATABASE: tournoix_test_db
  DB_USER: root
  DB_PASSWORD: root

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      # Run sql script to create tables and insert data
      - name: Run sql script
        run: mysql -h localhost -u root -proot test < ./test.sql

      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "./backend/.cargo\n ./backend/target\n ./ui/.cargo\n ./ui/target"
          shared-key: "rust_cache"

      - name: Build frontend
        run: cd ./ui && npm i && npm run build

      - name: Run backend tests
        run: cd ./backend && cargo test --release --verbose

    