name: Rust

on:
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always
  API_ENDPOINT: https://tournoix.ch/api
  APP_URL: https://tournoix.ch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - uses: jetli/trunk-action@v0.4.0
      with:
        version: 'latest'

    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: wasm32-unknown-unknown

    - uses: Swatinem/rust-cache@v2
      with:
        cache-directories: "./backend/.cargo\n ./backend/target\n ./ui/.cargo\n ./ui/target"
        shared-key: "rust_cache"

    - name: Build frontend
      run: cd ./ui && npm i && npm run build

    - name: Run backend tests
      run: cd ./backend && cargo test --release --verbose
